# Generated by Django 3.1.2 on 2020-11-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
