# Generated by Django 3.1.2 on 2020-10-26 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_code', models.CharField(max_length=128, unique=True)),
                ('birth_date', models.DateField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('failed_attempt', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
