# Generated by Django 3.1.2 on 2020-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='athlete_code',
            field=models.CharField(max_length=128),
        ),
    ]
