# Generated by Django 3.1.2 on 2020-11-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 19, 9, 43, 703839)),
        ),
    ]
